version: '2'
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
     - .:/usr/src/app
    ports:
     - "9000:9000"
    environment:
      MONGO_DB_URL: "mongo:27017/series_helper"
    links:
      - mongo
  mongo:
    image: mongo